[package]
name = "btc-black-hole-rust"
version = "0.1.0"
edition = "2021"

# Optional: Update description, authors, and license
description = "A Bitcoin address checksum brute-force GUI tool."
authors = ["Your Name <youremail@example.com>"]
license = "MIT"

# Define the binary
[[bin]]
name = "btc-black-hole-rust"
path = "src/main.rs"

[dependencies]
eframe = "0.22"
egui = "0.22"
base58 = "0.1.0"
sha2 = "0.10"
crossbeam = "0.8"
num_cpus = "1.13"