[package]
name = "btc_black_hole_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
sha2 = "0.10.6"
clap = { version = "4.0.32", features = ["derive"] }
num_cpus = "1.13.1"
crossbeam = "0.8.2"